on: 
  push:
    branches: master 
  pull_request:
    branches: master
  schedule: 
    - cron: '* 23 * * *'

name: fetch-people

jobs:
  fetch-people:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "googlesheets4", "tidyverse",
            "glue", "janitor", "rlang", "here", "stringr"))
        shell: Rscript {0}
        
      - name: Run script to fetch people
        run: Rscript --vanilla ./R/fetch-people.R
      - name: Commit files
        run: |
          echo ${{ github.ref }}
          git add .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "automated people update" -a | exit 0
      - name: Push changes
        if: github.ref == 'refs/heads/master'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
